getoutreach/stencil-base

manifest.yaml
This PR modifies the post-run command to include the edgecase of when a dependency is resolved differently with Go 1.16 than the current version of Go (1.17) and enables it to properly be resolved.
=> feat: compat go mod tidy

README.md.tpl
The deleted portion appears to be just instructions on how to create the API token.
Hopefully this is the last one 🤞 🤞 
CC: @george-e-shaw-iv
=> fix(circleci): fix token format

manifest.yaml
**What this PR does**: Updates the declared name to match the import path, which stencil now requires. This is purely a NOOP in current stencil versions, it's only used for extension repositories which this repository doesn't expose.
=> fix(manifest): update name to match new stencil requirements

manifest.yaml
**What this PR does**: No longer requires `oss` to be set. This was accidental.
=> fix: don't require oss to be set

templates/documentation/deployments.md.tpl, templates/documentation/runbooks/available-pods-low.md.tpl, templates/documentation/runbooks/grpc-latency-high.md.tpl, templates/documentation/runbooks/grpc-success-rate-low.md.tpl, templates/documentation/runbooks/http-latency-high.md.tpl, templates/documentation/runbooks/http-success-rate-low.md.tpl, templates/documentation/runbooks/pod-cpu.md.tpl, templates/documentation/runbooks/pod-memory.md.tpl, templates/documentation/runbooks/pod-restarts.md.tpl, templates/documentation/runbooks/service-panics.md.tpl
While updating the runbooks for the usermanager service to be compatible with bootstrap v10 in https://github.com/getoutreach/usermanager/pull/284 it was suggested that most of the details in the runbooks for usermanager was generally applicable to all services. The changes in this PR migrate the instructions from the usermanager runbooks to the common stencil-base runbook templates to make them more generally available for all services and improve the quality of the the runbooks for all.
I also left configurable blocks in all sections to allow teams to extend each section of the runbooks with service specific details as appropriate.
[EG-487]
[EG-487]: https://outreach-io.atlassian.net/browse/EG-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> feat(runbooks): Add details and instructions to runbooks [EG-487]

templates/README.md.tpl
In clerkschema we want to have an argoCD badge for our (own) prod deployment right on the README.
[CDT-00]
=> fix: allow services/libs to add extra badges

templates/.tool-versions.tpl
If tool-versions have the same tool listed twice, ASDF picks the first (not the last). This renders the override block ineffective because defaults always force ASDF to pick them. This is causing troubles to services repo - this repo needs older protoc version due to a bug in the latest protoc releases (https://github.com/protocolbuffers/protobuf-javascript/issues/127) but the clerk team pushes to latest one now, breaking the services repo.
The only two repos impacted are services and authz. I will manually test and update both of the repos to prepare them for V11 bootstrap after this PR merges. Other repos that provide tools in the tool versions override only add new ones - those won't be impacted.
[DT-2839]
[DT-2839]: https://outreach-io.atlassian.net/browse/DT-2839?atlOrigin=eyJpIjoiNWR …
=> fix: put ASDF tool ver overrides above default provisioned

templates/.gitignore.tpl
Adds `.dir-locals.el` to the `.gitignore` template's editor section to ignore local project variables set for Emacs.
[XX-XX]
=> chore: add .dir-locals.el to .gitignore

manifest.yaml
This drops support for 1.16 versions of modules. We still have the same issue with plain `go mod tidy` producing the below error message, but this lets us grab newer versions of packages.
Error message sample:
```
github.com/getoutreach/devbase/v2/root imports
github.com/opslevel/opslevel-go/v2022 imports
golang.org/x/oauth2 loaded from golang.org/x/oauth2@v0.0.0-20220608161450-d0670ef3b1eb,
but go 1.16 would select v0.0.0-20220622183110-fd043fe589d2
github.com/getoutreach/devbase/v2/root imports
github.com/opslevel/opslevel-go/v2022 imports
golang.org/x/oauth2 imports
golang.org/x/oauth2/internal loaded from golang.org/x/oauth2@v0.0.0-20220608161450-d0670ef3b1eb,
but go 1.16 would select v0.0.0-20220622183110-fd043fe589d2
To upgrade to the versions selected by go 1.16:
go mod tidy …
```
=> fix: drop go 1.16 support in go mod tidy

manifest.yaml
Fixes a conflict between stencil-base and stencil-circleci providing conflicting versions. 
Will also update a PR to fix this here: https://github.com/getoutreach/stencil-circleci/blob/b3ea44dd28034ed2283b32132e0459dd1dcaa023/manifest.yaml#L5
[DT-3489]
[DT-3489]: https://outreach-io.atlassian.net/browse/DT-3489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: set manifest.yaml devbase version to rc

manifest.yaml
Some generators require code to be formatted / compilable before they can be run, so try `make fmt` before and then after. Also, separate the steps to make it more clear which one failed.
This isn't a good long-term solution, to be clear, but it's the best quick hack I can think of.
=> fix(postRun): run fmt before gogenerate

templates/.gitignore.tpl
add hook to allow add more gitignore from other modules
[[DSC-10572](https://outreach-io.atlassian.net/browse/DSC-10572)]
Tested the usage from local runs. Usages example is [here](https://github.com/getoutreach/stencil-ds-python-service/pull/1/files#diff-b525da928b7e87c7ecb0453434bfc81795e0c07f96fdfc5e220fd1a7b2621f39)
[DSC-10572]: https://outreach-io.atlassian.net/browse/DSC-10572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add hook to allow add more gitignore from other modules

manifest.yaml
Removes an `rc` import that was left over during the last release. Also removes the schema for `serviceActivities` since it's duplicative and not the authority on valid values. Instead `stencil-golang` should error/validate the values.
[XX-XX]
=> fix(manifest): remove rc import, remove duplicated schema for serviceActivies

manifest.yaml
This PR fixes stencil-base to depend on `devbase`, because it does with it's post run commands :D 
[XX-XX]
=> fix(manifest): depend on stencil-base

package.json, templates/package.json.tpl, yarn.lock
Upgrades `semantic-release` to v21 to support new ESM modules being used
in the dependency chain.
=> feat(semantic-release): v21

templates/CONTRIBUTING.md.tpl, templates/README.md.tpl
These doc files have been very inflexible for teams to write useful documentation on top of, and hence the vast majority of services have exactly this doc available out of the box with no changes.  This change will allow teams to do whatever they desire with the README docs.
=> feat: Moving README and CONTRIBUTING files to be Static

.github/pull_request_template.md, templates/.github/pull_request_template.md.tpl, templates/.snapshots/TestRenderPullRequestTemplateFile-.github-pull_request_template.md.tpl-.github-pull_request_template.md.snapshot
This is a more useful document _and _ works for open-source projects.
=> fix: Link to a non-Outreach definition of conventional commits.

manifest.yaml
asdf_install is just an alias for asdf_devbase_ensure.
=> fix: Remove call to deprecated function.

templates/.snapshots/TestRenderReadmeFile-README.md.tpl-README.md.snapshot, templates/CONTRIBUTING.md.tpl, templates/README.md.tpl, templates/main_test.go
Removed instances where the GitHub org name was hardcoded, which makes it difficult to use outside of Outreach.
=> fix: use box to populate org name

manifest.yaml, templates/.github/CODEOWNERS.tpl, templates/.snapshots/TestRenderCodeownersFile-.github-CODEOWNERS.tpl-.github-CODEOWNERS.snapshot, templates/.snapshots/TestRenderCodeownersWithExtraOwnersFile-.github-CODEOWNERS.tpl-.github-CODEOWNERS.snapshot, templates/main_test.go
Does what it says on the tin, with some snapshot tests.
Also removes some trailing whitespace.
[DT-4130]
[DT-4130]: https://outreach-io.atlassian.net/browse/DT-4130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add additionalRepoOwners to specify repo co-owners

templates/main_test.go
Does what it says on the tin, so we can regenerate snapshots locally but have a rendered snapshot diff in CI.
=> test: use stenciltest.RegenerateSnapshots()

templates/.releaserc.yaml.tpl, templates/.snapshots/TestReleaseRCForLibrary-.releaserc.yaml.tpl-.releaserc.yaml.snapshot, templates/.snapshots/TestReleaseRCWithNodeJSGRPCClient-.releaserc.yaml.tpl-.releaserc.yaml.snapshot, templates/.snapshots/TestReleaseRCWithRubyGRPCClient-.releaserc.yaml.tpl-.releaserc.yaml.snapshot, templates/main_test.go
Does what it says on the tin. Also adds snapshots for various gRPC client permutations.
[DT-4300]
[DT-4300]: https://outreach-io.atlassian.net/browse/DT-4300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(semantic-release): allow libraries to release gRPC packages

.tool-versions, package.json, scripts/.tool-versions, templates/package.json.tpl, yarn.lock
This should resolve a bunch of Dependabot alerts on stenciled repos.
This is part 1 of 2 PRs. The other PR is in `stencil-golang` to update the Node.js version for build tooling.
[DT-4322]
[DT-4322]: https://outreach-io.atlassian.net/browse/DT-4322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: upgrade semantic-release to 23.0.8

manifest.yaml
Replacement fix for #169. I tested this with an existing service by adding a local replacement directive in `service.yaml` and running the below steps.
[DT-4444]
Repro steps:
1. Clone any stenciled repo
2. Run `rm yarn.lock`
3. Run `stencil`
Expected: Works, `yarn.lock` recreated with possibly new changes
Actual: `yarn upgrade` fails, which causes `stencil` to fail
Closes #169.
[DT-4444]: https://outreach-io.atlassian.net/browse/DT-4444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: post-run yarn if yarn.lock does not exist

templates/package.json.tpl
Companion PR to https://github.com/getoutreach/devbase/pull/936 (context available there)
=> fix: remove obsolete hjson Node.js dependency

templates/.snapshots/TestRenderMiseTOML-mise.toml.tpl-mise.toml.snapshot, templates/mise.toml.tpl
Otherwise the `customMiseEnvironment` block doesn't make sense. It appears that an empty `[env]` section is fine with `mise`.
=> fix(mise): always emit env section

manifest.yaml
This should take care of adding/removing direct dependencies, as `yarn upgrade` fails without it.
=> fix(postrun): always run `yarn`, conditionally run `yarn upgrade`
