getoutreach/stencil-base

README.md.tpl
documentation/README.md.tpl
documentation/SLOs.md.tpl
documentation/disaster-recovery.md.tpl
documentation/rollout-plan.md.tpl
documentation/runbook.md.tpl
manifest.yaml

https://github.com/getoutreach/bootstrap/pull/954

feat: opslevel stuff

---

README.md.tpl

Fix CONTRIBUTING link now that #4 was merged, & remove some trailing whitespace.

fix: minor README updates

---

.github/CODEOWNERS.tpl
.github/pull_request_template.md.tpl
.gitignore.tpl
.releaserc.yaml.tpl
CONTRIBUTING.md.tpl
README.md.tpl
documentation/README.md.tpl
documentation/SLOs.md.tpl
documentation/disaster-recovery.md.tpl
documentation/rollout-plan.md.tpl
documentation/runbook.md.tpl
helpers.tpl
manifest.yaml
package.json.tpl
scripts/bootstrap-lib.sh.tpl
scripts/devbase.sh.tpl
scripts/shell-wrapper.sh.tpl

This PR updates the templates to support the new stencil block system.

feat: support new stencil block format

---

documentation/runbook.md.tpl

**What this PR does**: Fixes the runbook docs to properly render

fix(documentation/runbook): properly handle forceRender vs Service

---

templates/documentation/README.md.tpl
templates/documentation/SLOs.md.tpl
templates/documentation/disaster-recovery.md.tpl
templates/documentation/rollout-plan.md.tpl
templates/documentation/runbook.md.tpl

* bug in file.Skip conditional
[XX-XX]

fix: docs render logic

---

templates/CONTRIBUTING.md.tpl

docs(contributing): fix typo

---

templates/.releaserc.yaml.tpl

fix: add block to .releaserc.yaml

---

templates/documentation/runbook.md.tpl
templates/documentation/runbooks/available-pods-low.md.tpl
templates/documentation/runbooks/grpc-latency-high.md.tpl
templates/documentation/runbooks/grpc-success-rate-low.md.tpl
templates/documentation/runbooks/http-latency-high.md.tpl
templates/documentation/runbooks/http-success-rate-low.md.tpl
templates/documentation/runbooks/pod-cpu.md.tpl
templates/documentation/runbooks/pod-memory.md.tpl
templates/documentation/runbooks/pod-restarts.md.tpl
templates/documentation/runbooks/service-panics.md.tpl

* design based off of this conversation: https://outreach-hq.slack.com/archives/C01CAR6GVPD/p1652733288900979
[XX-XX]

feat: runbooks refactor

---

templates/documentation/runbook.md.tpl

fix(runbook): typo

---

templates/documentation/runbook.md.tpl
templates/documentation/runbooks/available-pods-low.md.tpl
templates/documentation/runbooks/grpc-latency-high.md.tpl
templates/documentation/runbooks/grpc-success-rate-low.md.tpl
templates/documentation/runbooks/http-latency-high.md.tpl
templates/documentation/runbooks/http-success-rate-low.md.tpl
templates/documentation/runbooks/pod-cpu.md.tpl
templates/documentation/runbooks/pod-memory.md.tpl
templates/documentation/runbooks/pod-restarts.md.tpl
templates/documentation/runbooks/service-panics.md.tpl

* confluence indexes on page name no matter where it is at in the
hierarchy.
[XX-XX]

fix: prefix md page names with service

---

templates/documentation/runbooks/pod-cpu.md.tpl

Bad block name is causing bootstrap failures.
[XX-XX]

fix: correct spelling in block name

---

templates/documentation/runbooks/available-pods-low.md.tpl
templates/documentation/runbooks/grpc-success-rate-low.md.tpl
templates/documentation/runbooks/pod-restarts.md.tpl

This fixes the links between several of the runbooks that were incorrect in #36 .
[EG-487]
[EG-487]: https://outreach-io.atlassian.net/browse/EG-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(runbooks): Fix documentation links in runbooks [EG-487]

---

templates/documentation/deployments.md.tpl
templates/documentation/runbooks/available-pods-low.md.tpl
templates/documentation/runbooks/grpc-latency-high.md.tpl
templates/documentation/runbooks/grpc-success-rate-low.md.tpl
templates/documentation/runbooks/http-latency-high.md.tpl
templates/documentation/runbooks/http-success-rate-low.md.tpl
templates/documentation/runbooks/pod-cpu.md.tpl
templates/documentation/runbooks/pod-memory.md.tpl
templates/documentation/runbooks/pod-restarts.md.tpl
templates/documentation/runbooks/service-panics.md.tpl

This is an automatically generated release PR created by [`create-pr.sh`](https://github.com/getoutreach/dtss-tools/tree/main/release).
This PR should **NOT BE MERGED THROUGH THE GITHUB UI**, instead run `merge-release-prs.sh <repo>` instead.

chore(release): 07/25/22

---

manifest.yaml

Rewrites `manifest.yaml` in the schema format so the applications can understand it better.
[DT-2524]
[DT-2524]: https://outreach-io.atlassian.net/browse/DT-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Rewrite manifest.yaml in schema format

---

manifest.yaml
templates/.releaserc.yaml.tpl

* add a release option to force the render of make release in
releaserc.yaml
[XX-XX]

fix: plugin releasing

---

.circleci/config.yml
.github/CODEOWNERS
.releaserc.yaml
.tool-versions
CONTRIBUTING.md
README.md
bootstrap.lock
service.yaml
stencil.lock

fix: fnd-dt, re-run stencil

---

manifest.yaml
scripts/.tool-versions
templates/.releaserc.yaml.tpl

Allows setting pre-releases branch. Automatic branch creation will be handled in https://outreach-io.atlassian.net/browse/DT-2633.
[DT-2624]
[DT-2624]: https://outreach-io.atlassian.net/browse/DT-2624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow setting prereleasesBranch

---

templates/package.json.tpl

fix(node-deps): upgrade node deps

---

.circleci/config.yml
.tool-versions
README.md
bootstrap.lock
go.mod
go.sum
package.json
stencil.lock
yarn.lock

fix: re-stencil

---

templates/.tool-versions.tpl

Floats don't turn into strings nicely in printf :cry:
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tool-versions): always toString version

---

templates/documentation/runbooks/pod-cpu.md.tpl

fix: add missing start block

---

templates/documentation/runbooks/pod-cpu.md.tpl

Promote unstable to rc, created by `dt release promote`

Promote unstable to rc

---

templates/README.md.tpl

PR diff says it better than I could 😄 
[DT-0]

docs(README): typo

---

templates/documentation/rate-limiting-strategy.md.tpl
templates/documentation/scaling-plan.md.tpl

These files are required by opslevel
[XX-XX]

feat: required md files

---

manifest.yaml

See comment in `manifest.yaml` for why.
[XX-XX]

fix(manifest): depend on stencil-circleci v1.4.0-rc.1

---

manifest.yaml

Promote unstable to rc, created by `dt release promote`

chore: Promote unstable to rc

---

manifest.yaml

Changes the order of post run commands in order to better support code generation.
[DT-2878]
[DT-2878]: https://outreach-io.atlassian.net/browse/DT-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(postRunCommand): run gogenerate before tidy

---

manifest.yaml

Removes all manifest rc dependency to prevent breakage in released stable modules.
[XX-XX]

fix: remove manifest rc dependency

---

manifest.yaml

Hotfixes commit "69c19b11a6046e8fadc826237969a5c3969d4061" into channel stable, created by `dt release hotfix`

chore: Hotfix 69c19b11a6046e8fadc826237969a5c3969d4061 into channel stable

---

.circleci/config.yml
.tool-versions
.vscode/launch.json
scripts/golangci.yml
service.yaml
stencil.lock

Switches to stable version of all module and re-stencils. Test of full release.
[XX-XX]

fix: re-stencil 11-29-2022

---

manifest.yaml
templates/README.md.tpl

Showing test generation https://github.com/getoutreach/orgservice/pull/655

fix(STAR-790): add instructions for iteracting with temporal

---

.gitignore
go.mod
go.sum
service.yaml
stencil.lock

restencil for [testing RC changes](https://outreach-io.atlassian.net/wiki/spaces/DT/pages/2388198102/SOP+Releasing+Dev+Tooling+Updates#Testing-RC-changes)
[XX-XX]

fix: restencil for testing RC changes

---

templates/CONTRIBUTING.md.tpl

TODO :D
[DT-3189]
[DT-3189]: https://outreach-io.atlassian.net/browse/DT-3189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(README): link to devbase documentation (DT-3189)

---

.circleci/config.yml
service.yaml
stencil.lock

Skips e2e test since we don't have any, and skips docker since it will no longer work with the newest devbase.
[XX-XX]

fix: skip docker and e2e steps in CI

---

.circleci/config.yml
monitoring/slos.tf
service.yaml
stencil.lock

Removes `stencil-discover` as a dependency.
[DT-3385]
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove private modules

---

service.yaml
stencil.lock

Uses rc versions that do not depend on stencil-discovery.
[DT-3385](https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dependencies without discovery

---

.circleci/config.yml
.gitignore
CONTRIBUTING.md
go.mod
go.sum
manifest.yaml
monitoring/slos.tf
service.yaml
stencil.lock
templates/CONTRIBUTING.md.tpl

Promote rc to stable, created by `dt release promote`

chore: Promote rc to stable

---

.circleci/config.yml
.vscode/outreach.code-snippets
opslevel.yml
service.yaml
stencil.lock

fix(release): restencil for opslevel

---

README.md

add readme to pass opslevel silver
https://app.opslevel.com/services/stencil-base/maturity-report
[XX-XX]

chore: pass opslevel silver

---

manifest.yaml

Hotfixes commit(s) "6450933947a51a03f3ee5075360fe3ffaca7c8f0" into channel stable, created by `dt release hotfix`

chore: Hotfix 6450933947a51a03f3ee5075360fe3ffaca7c8f0 into channel stable

---

.circleci/config.yml
.github/dependabot.yml
go.mod
go.sum
opslevel.yml
service.yaml
stencil.lock

feat: restencil

---

.circleci/config.yml
.github/dependabot.yml
.vscode/launch.json
go.mod
go.sum
opslevel.yml
scripts/golangci.yml
stencil.lock

feat(stencil): restencil

---

templates/.github/pull_request_template.md.tpl
templates/.snapshots/TestRenderPullRequestTemplateFile-.github-pull_request_template.md.tpl-.github-pull_request_template.md.snapshot
templates/CONTRIBUTING.md.tpl
templates/main_test.go

added "contributeAdditionalInformation" module hook for CONTRIBUTING.md file for additional warnings
https://outreach-io.atlassian.net/browse/STAR-1302

feat: added "contributeAdditionalInformation" module hook for CONTRIBUTING.md file

---

templates/_helpers.tpl

chore: fix error message typo

---

cortex.yaml
manifest.yaml
stencil.lock
yarn.lock

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
- add `yarn` to postRun
[XX-XX]

fix(stencil): add yarn to postRun

---

manifest.yaml

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for additional information on contributing to this repository!
- remove yarn.lock 
[XX-XX]

fix(stencil): run yarn upgrade on postRun

---

.circleci/config.yml
scripts/golangci.yml
stencil.lock
yarn.lock

Merge tmp-release-stable-v0.16.4-rc.1 to release

chore: Release v0.16.4

---

templates/CONTRIBUTING.md.tpl

Noticed this while re-stenciling a repo.

fix(docs): typo in CONTRIBUTING.md
